import { HotelSummary, HotelDetail, HotelCardItem, Destination, HotelTabData, HotelMainData } from "@/domain/hotel/types";

const IMG = {
  // Destinations
  seoul:
    "https://images.unsplash.com/photo-1651836173046-e02e7627b9a6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=600",
  busan:
    "https://images.unsplash.com/photo-1735408713919-1f191ebfabd8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=600",
  jeju: "https://images.unsplash.com/photo-1602934198239-ff2e47d124f8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=600",
  gangwon:
    "https://images.unsplash.com/photo-1768141919912-d20b8f4119fe?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=600",
  gyeongju:
    "https://images.unsplash.com/photo-1643784946065-e58f1f8a4d20?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=600",
  // Overseas
  tokyo:
    "https://images.unsplash.com/photo-1734586117486-667069f3696b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=600",
  osaka:
    "https://images.unsplash.com/photo-1705695469571-f30d7a2140e4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=600",
  danang:
    "https://images.unsplash.com/flagged/photo-1583863374731-4224cbbc8c36?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=600",
  paris:
    "https://images.unsplash.com/photo-1642947392578-b37fbd9a4d45?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=600",
  bangkok:
    "https://images.unsplash.com/photo-1729486120684-89d2cb90f360?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=600",
  singapore:
    "https://images.unsplash.com/photo-1727880676753-9ba90268d3ce?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=600",
  bali: "https://images.unsplash.com/photo-1559998560-deb30d24ea50?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=600",
  fukuoka:
    "https://images.unsplash.com/photo-1752400717588-55e83afd4745?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=600",
  // Hotel interiors
  h1: "https://images.unsplash.com/photo-1592899940134-3161736713c9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=600",
  h2: "https://images.unsplash.com/photo-1624558118561-325bc4933964?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=600",
  h3: "https://images.unsplash.com/photo-1609602126247-4ab7188b4aa1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=600",
  h4: "https://images.unsplash.com/photo-1667842288007-ea49b67ce9cf?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=600",
  h5: "https://images.unsplash.com/photo-1759223198981-661cadbbff36?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=600",
  h6: "https://images.unsplash.com/photo-1768913573689-fa59c3c061cc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=600",
  h7: "https://images.unsplash.com/photo-1757434679729-c4f905ef2feb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=600",
  h8: "https://images.unsplash.com/photo-1717920954821-4cb46139f19e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=600",
};
// ─── 호캉스 tabs ─────────────────────────────────────────────────────────────
export const mockHotelMainhokangs: {
  seoulHotels: HotelCardItem[];
  busanHotels: HotelCardItem[];
  jejuHotels: HotelCardItem[];
  gangwonHotels: HotelCardItem[];
  gyeongjuHotels: HotelCardItem[];
  overseasTabs: HotelTabData[];
} = {
  // ─── Seoul Hotels ────────────────────────────────────────────────────────────
  seoulHotels: [
    {
      id: "s1",
      name: "그랜드 하얏트 서울",
      location: "서울 · 용산구",
      image: IMG.h2,
      rating: 4.92,
      reviewCount: 3842,
      originalPrice: 480000,
      price: 312000,
      discount: 35,
      promoTags: ["기간한정"],
      isLowestPrice: true,
    },
    {
      id: "s2",
      name: "롯데호텔 서울",
      location: "서울 · 중구",
      image: IMG.h1,
      rating: 4.87,
      reviewCount: 5120,
      originalPrice: 390000,
      price: 273000,
      discount: 30,
      promoTags: ["조식포함"],
      isAI: true,
    },
    {
      id: "s3",
      name: "시그니엘 서울",
      location: "서울 · 송파구",
      image: IMG.h6,
      rating: 4.95,
      reviewCount: 2210,
      price: 620000,
      promoTags: ["BEST"],
      isLowestPrice: true,
    },
    {
      id: "s4",
      name: "조선 팰리스 서울",
      location: "서울 · 강남구",
      image: IMG.h5,
      rating: 4.88,
      reviewCount: 1840,
      originalPrice: 510000,
      price: 408000,
      discount: 20,
      isAI: true,
    },
    {
      id: "s5",
      name: "파크하얏트 서울",
      location: "서울 · 강남구",
      image: IMG.h3,
      rating: 4.9,
      reviewCount: 2990,
      originalPrice: 450000,
      price: 337500,
      discount: 25,
      promoTags: ["기간한정"],
    },
    {
      id: "s6",
      name: "더 플라자 호텔",
      location: "서울 · 중구",
      image: IMG.h4,
      rating: 4.83,
      reviewCount: 4100,
      price: 285000,
      promoTags: ["조식포함"],
      isLowestPrice: true,
    },
  ],

  // ─── Busan Hotels ────────────────────────────────────────────────────────────
  busanHotels: [
    {
      id: "b1",
      name: "파라다이스 호텔 부산",
      location: "부산 · 해운대구",
      image: IMG.h7,
      rating: 4.91,
      reviewCount: 3210,
      originalPrice: 420000,
      price: 252000,
      discount: 40,
      promoTags: ["기간한정", "조식포함"],
      isLowestPrice: true,
    },
    {
      id: "b2",
      name: "해운대 그랜드 호텔",
      location: "부산 · 해운대구",
      image: IMG.h3,
      rating: 4.85,
      reviewCount: 2780,
      originalPrice: 320000,
      price: 224000,
      discount: 30,
      isAI: true,
    },
    {
      id: "b3",
      name: "시그니엘 부산",
      location: "부산 · 해운대구",
      image: IMG.h6,
      rating: 4.93,
      reviewCount: 1960,
      price: 520000,
      promoTags: ["BEST"],
      isLowestPrice: true,
    },
    {
      id: "b4",
      name: "롯데호텔 부산",
      location: "부산 · 남구",
      image: IMG.h2,
      rating: 4.82,
      reviewCount: 4320,
      originalPrice: 280000,
      price: 196000,
      discount: 30,
    },
    {
      id: "b5",
      name: "부산 웨스틴 조선",
      location: "부산 · 해운대구",
      image: IMG.h5,
      rating: 4.88,
      reviewCount: 2100,
      originalPrice: 380000,
      price: 285000,
      discount: 25,
      promoTags: ["조식포함"],
    },
    {
      id: "b6",
      name: "호텔 인디고 부산",
      location: "부산 · 중구",
      image: IMG.h8,
      rating: 4.79,
      reviewCount: 1580,
      price: 195000,
      isAI: true,
    },
  ],
  // ─── Jeju Hotels ─────────────────────────────────────────────────────────────
  jejuHotels: [
    {
      id: "j1",
      name: "제주 신라호텔",
      location: "제주 · 서귀포시",
      image: IMG.h4,
      rating: 4.94,
      reviewCount: 5430,
      originalPrice: 550000,
      price: 385000,
      discount: 30,
      promoTags: ["기간한정"],
      isLowestPrice: true,
    },
    {
      id: "j2",
      name: "롯데호텔 제주",
      location: "제주 · 서귀포시",
      image: IMG.h7,
      rating: 4.87,
      reviewCount: 4200,
      originalPrice: 420000,
      price: 294000,
      discount: 30,
      isAI: true,
    },
    {
      id: "j3",
      name: "아난티 코브 제주",
      location: "제주 · 제주시",
      image: IMG.h5,
      rating: 4.92,
      reviewCount: 2870,
      price: 680000,
      promoTags: ["BEST"],
      isLowestPrice: true,
    },
    {
      id: "j4",
      name: "히든클리프 제주",
      location: "제주 · 서귀포시",
      image: IMG.h3,
      rating: 4.96,
      reviewCount: 1420,
      originalPrice: 480000,
      price: 336000,
      discount: 30,
      promoTags: ["기간한정"],
    },
    {
      id: "j5",
      name: "제주 파르나스 호텔",
      location: "제주 · 제주시",
      image: IMG.h1,
      rating: 4.84,
      reviewCount: 3100,
      originalPrice: 350000,
      price: 262500,
      discount: 25,
      isAI: true,
    },
    {
      id: "j6",
      name: "제주 오리엔탈 호텔",
      location: "제주 · 제주시",
      image: IMG.h8,
      rating: 4.78,
      reviewCount: 2650,
      price: 175000,
      isLowestPrice: true,
    },
  ],
  // ─── Gangwon Hotels ──────────────────────────────────────────────────────────
  gangwonHotels: [
    {
      id: "g1",
      name: "세인트존스 강릉",
      location: "강원 · 강릉시",
      image: IMG.h2,
      rating: 4.89,
      reviewCount: 2940,
      originalPrice: 380000,
      price: 228000,
      discount: 40,
      promoTags: ["기간한정"],
      isLowestPrice: true,
    },
    {
      id: "g2",
      name: "씨마크 호텔 강릉",
      location: "강원 · 강릉시",
      image: IMG.h7,
      rating: 4.86,
      reviewCount: 3560,
      originalPrice: 320000,
      price: 224000,
      discount: 30,
      isAI: true,
    },
    {
      id: "g3",
      name: "롯데리조트 속초",
      location: "강원 · 속초시",
      image: IMG.h4,
      rating: 4.91,
      reviewCount: 2100,
      originalPrice: 450000,
      price: 225000,
      discount: 50,
      promoTags: ["기간한정", "조식포함"],
    },
    {
      id: "g4",
      name: "하이원 그랜드 호텔",
      location: "강원 · 정선군",
      image: IMG.h6,
      rating: 4.82,
      reviewCount: 1870,
      price: 290000,
      isLowestPrice: true,
    },
    {
      id: "g5",
      name: "알펜시아 리조트",
      location: "강원 · 평창군",
      image: IMG.h8,
      rating: 4.85,
      reviewCount: 2430,
      originalPrice: 390000,
      price: 273000,
      discount: 30,
      isAI: true,
    },
    {
      id: "g6",
      name: "한화리조트 설악",
      location: "강원 · 속초시",
      image: IMG.h5,
      rating: 4.77,
      reviewCount: 3200,
      originalPrice: 250000,
      price: 175000,
      discount: 30,
    },
  ],
  // ─── Gyeongju Hotels ─────────────────────────────────────────────────────────
  gyeongjuHotels: [
    {
      id: "gy1",
      name: "힐튼 경주",
      location: "경북 · 경주시",
      image: IMG.h1,
      rating: 4.9,
      reviewCount: 2310,
      originalPrice: 340000,
      price: 238000,
      discount: 30,
      promoTags: ["조식포함"],
      isLowestPrice: true,
    },
    {
      id: "gy2",
      name: "라한셀렉트 경주",
      location: "경북 · 경주시",
      image: IMG.h3,
      rating: 4.83,
      reviewCount: 1850,
      price: 195000,
      isAI: true,
    },
    {
      id: "gy3",
      name: "더케이호텔 경주",
      location: "경북 · 경주시",
      image: IMG.h5,
      rating: 4.79,
      reviewCount: 2140,
      originalPrice: 280000,
      price: 196000,
      discount: 30,
    },
    {
      id: "gy4",
      name: "코모도 경주",
      location: "경북 · 경주시",
      image: IMG.h8,
      rating: 4.75,
      reviewCount: 980,
      price: 155000,
      isLowestPrice: true,
    },
    {
      id: "gy5",
      name: "신라스테이 경주",
      location: "경북 · 경주시",
      image: IMG.h2,
      rating: 4.81,
      reviewCount: 1560,
      originalPrice: 210000,
      price: 147000,
      discount: 30,
    },
  ],
  // ─── Overseas – Japan Tabs ───────────────────────────────────────────────────
  overseasTabs: [
    {
      label: "일본",
      hotels: [
        {
          id: "oj1",
          name: "하얏트 리젠시 도쿄",
          location: "일본 · 도쿄",
          image: IMG.tokyo,
          rating: 4.89,
          reviewCount: 6240,
          originalPrice: 320000,
          price: 192000,
          discount: 40,
          tags: ["신주쿠뷰"],
        },
        {
          id: "oj2",
          name: "더 리츠칼튼 오사카",
          location: "일본 · 오사카",
          image: IMG.osaka,
          rating: 4.93,
          reviewCount: 4100,
          price: 420000,
          tags: ["럭셔리"],
        },
        {
          id: "oj3",
          name: "하카타 엑셀 호텔",
          location: "일본 · 후쿠오카",
          image: IMG.fukuoka,
          rating: 4.8,
          reviewCount: 3280,
          originalPrice: 180000,
          price: 126000,
          discount: 30,
        },
        {
          id: "oj4",
          name: "더 페닌슐라 도쿄",
          location: "일본 · 도쿄",
          image: IMG.h6,
          rating: 4.95,
          reviewCount: 2870,
          price: 580000,
          tags: ["프리미엄", "긴자"],
        },
        {
          id: "oj5",
          name: "오사카 힐튼",
          location: "일본 · 오사카",
          image: IMG.h2,
          rating: 4.85,
          reviewCount: 3950,
          originalPrice: 260000,
          price: 182000,
          discount: 30,
        },
      ],
    },
    {
      label: "동남아",
      hotels: [
        {
          id: "ose1",
          name: "아난타라 방콕",
          location: "태국 · 방콕",
          image: IMG.bangkok,
          rating: 4.91,
          reviewCount: 5430,
          originalPrice: 280000,
          price: 168000,
          discount: 40,
          tags: ["루프탑풀"],
        },
        {
          id: "ose2",
          name: "마리나베이샌즈",
          location: "싱가포르",
          image: IMG.singapore,
          rating: 4.88,
          reviewCount: 9870,
          price: 620000,
          tags: ["인피니티풀"],
        },
        {
          id: "ose3",
          name: "인터컨티넨탈 다낭",
          location: "베트남 · 다낭",
          image: IMG.danang,
          rating: 4.92,
          reviewCount: 3210,
          originalPrice: 350000,
          price: 245000,
          discount: 30,
          tags: ["오션뷰"],
        },
        {
          id: "ose4",
          name: "포시즌스 발리",
          location: "인도네시아 · 발리",
          image: IMG.bali,
          rating: 4.94,
          reviewCount: 2650,
          price: 480000,
          tags: ["빌라", "프라이빗풀"],
        },
        {
          id: "ose5",
          name: "리츠칼튼 방콕",
          location: "태국 · 방콕",
          image: IMG.h4,
          rating: 4.89,
          reviewCount: 4120,
          originalPrice: 320000,
          price: 224000,
          discount: 30,
        },
      ],
    },
    {
      label: "유럽",
      hotels: [
        {
          id: "oeu1",
          name: "포시즌스 파리",
          location: "프랑스 · 파리",
          image: IMG.paris,
          rating: 4.96,
          reviewCount: 3870,
          price: 890000,
          tags: ["에펠탑뷰", "럭셔리"],
        },
        {
          id: "oeu2",
          name: "더 사보이 런던",
          location: "영국 · 런던",
          image: IMG.h1,
          rating: 4.93,
          reviewCount: 5200,
          price: 720000,
          tags: ["클래식"],
        },
        {
          id: "oeu3",
          name: "호텔 임페리얼 빈",
          location: "오스트리아 · 빈",
          image: IMG.h5,
          rating: 4.91,
          reviewCount: 2430,
          price: 650000,
          tags: ["역사적"],
        },
        {
          id: "oeu4",
          name: "바르셀로나 W호텔",
          location: "스페인 · 바르셀로나",
          image: IMG.h6,
          rating: 4.87,
          reviewCount: 4100,
          originalPrice: 580000,
          price: 406000,
          discount: 30,
          tags: ["해변"],
        },
        {
          id: "oeu5",
          name: "바우어 팔라초 베네치아",
          location: "이탈리아 · 베네치아",
          image: IMG.h3,
          rating: 4.89,
          reviewCount: 1980,
          price: 780000,
        },
      ],
    },
    {
      label: "미주/하와이",
      hotels: [
        {
          id: "oam1",
          name: "더 비버리힐스 호텔",
          location: "미국 · LA",
          image: IMG.h7,
          rating: 4.92,
          reviewCount: 3400,
          price: 820000,
          tags: ["할리우드"],
        },
        {
          id: "oam2",
          name: "포시즌스 마우이",
          location: "미국 · 하와이",
          image: IMG.h4,
          rating: 4.95,
          reviewCount: 2870,
          price: 950000,
          tags: ["오션뷰", "비치"],
        },
        {
          id: "oam3",
          name: "더 플라자 뉴욕",
          location: "미국 · 뉴욕",
          image: IMG.h2,
          rating: 4.9,
          reviewCount: 5100,
          price: 780000,
          tags: ["맨하탄"],
        },
        {
          id: "oam4",
          name: "힐튼 와이키키",
          location: "미국 · 호놀룰루",
          image: IMG.h8,
          rating: 4.84,
          reviewCount: 4230,
          originalPrice: 680000,
          price: 476000,
          discount: 30,
        },
        {
          id: "oam5",
          name: "리츠칼튼 뉴욕",
          location: "미국 · 뉴욕",
          image: IMG.h5,
          rating: 4.93,
          reviewCount: 2960,
          price: 850000,
          tags: ["럭셔리"],
        },
      ],
    },
  ],
};
// ─── Hotel Main List ─────────────────────────────────────────────────────────────
export const mockHotelMainList: HotelMainData = {
  seoulHotels: mockHotelMainhokangs.seoulHotels,
  busanHotels: mockHotelMainhokangs.busanHotels,
  jejuHotels: mockHotelMainhokangs.jejuHotels,
  gangwonHotels: mockHotelMainhokangs.gangwonHotels,
  gyeongjuHotels: mockHotelMainhokangs.gyeongjuHotels,
  overseasTabs: mockHotelMainhokangs.overseasTabs,

  // ─── Hokangs tabs ─────────────────────────────────────────────────────────────
  hokangsTabs: [
    { label: "강원", hotels: mockHotelMainhokangs.gangwonHotels },
    { label: "제주", hotels: mockHotelMainhokangs.jejuHotels.slice(0, 5) },
    { label: "경상", hotels: mockHotelMainhokangs.gyeongjuHotels },
    {
      label: "충청",
      hotels: mockHotelMainhokangs.seoulHotels
        .slice(2, 6)
        .map((h, i) => ({ ...h, id: `hk${i}`, location: "충청 · 대전" })),
    },
  ],

  // ─── Domestic destinations ───────────────────────────────────────────────────
  domesticDests: [
    { name: "제주도", image: IMG.jeju, hotelCount: 1842 },
    { name: "서울", image: IMG.seoul, hotelCount: 5230 },
    { name: "부산", image: IMG.busan, hotelCount: 2180 },
    { name: "강원", image: IMG.gangwon, hotelCount: 1540 },
    { name: "경주", image: IMG.gyeongju, hotelCount: 620 },
    { name: "인천", image: IMG.h7, hotelCount: 980 },
  ],

  // ─── Overseas destinations ─────────────────────────────────────────────────────
  overseasDests: [
    { name: "도쿄", image: IMG.tokyo, hotelCount: 4320 },
    { name: "오사카", image: IMG.osaka, hotelCount: 3180 },
    { name: "다낭", image: IMG.danang, hotelCount: 1870 },
    { name: "방콕", image: IMG.bangkok, hotelCount: 2640 },
    { name: "싱가포르", image: IMG.singapore, hotelCount: 1920 },
    { name: "파리", image: IMG.paris, hotelCount: 3560 },
  ],
};
// ─── Hotel List ─────────────────────────────────────────────────────────────
export const mockHotelList: HotelSummary[] = [
  {
    id: "1",
    name: "그랜드 워커힐 서울",
    nameEn: "Grand Walkerhill Seoul",
    location: "서울 광진구",
    type: "HOTEL",
    stars: 5,
    rating: 4.8,
    originalPrice: 550000,
    discountPrice: 440000,
    discountRate: 20,
    thumbnailUrl:
      "https://images.unsplash.com/photo-1566073771259-6a8506099945",
  },
  {
    id: "2",
    name: "신라 호텔 제주",
    nameEn: "The Shilla Jeju",
    location: "제주 서귀포시",
    type: "HOTEL",
    stars: 5,
    rating: 4.9,
    originalPrice: 700000,
    discountPrice: 560000,
    discountRate: 20,
    thumbnailUrl:
      "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b",
  },
  {
    id: "3",
    name: "세인트존스 호텔",
    nameEn: "St. John's Hotel",
    location: "강원 강릉시",
    type: "HOTEL",
    stars: 4,
    rating: 4.2,
    originalPrice: 250000,
    discountPrice: 150000,
    discountRate: 40,
    thumbnailUrl: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb",
  },
  {
    id: "4",
    name: "아난티 앳 부산",
    nameEn: "Ananti at Busan",
    location: "부산 기장군",
    type: "RESORT",
    stars: 5,
    rating: 4.7,
    originalPrice: 800000,
    discountPrice: 720000,
    discountRate: 10,
    thumbnailUrl:
      "https://images.unsplash.com/photo-1571896349842-33c89424de2d",
  },
  {
    id: "5",
    name: "네스트 호텔 인천",
    nameEn: "Nest Hotel Incheon",
    location: "인천 중구",
    type: "HOTEL",
    stars: 5,
    rating: 4.5,
    originalPrice: 300000,
    discountPrice: 210000,
    discountRate: 30,
    thumbnailUrl:
      "https://images.unsplash.com/photo-1564501049412-61c2a3083791",
  },
  {
    id: "6",
    name: "파라다이스 시티",
    nameEn: "Paradise City",
    location: "인천 중구",
    type: "HOTEL",
    stars: 5,
    rating: 4.8,
    originalPrice: 450000,
    discountPrice: 382500,
    discountRate: 15,
    thumbnailUrl:
      "https://images.unsplash.com/photo-1445019980597-93fa8acb246c",
  },
  {
    id: "7",
    name: "히든 클리프 호텔",
    nameEn: "Hidden Cliff Hotel",
    location: "제주 서귀포시",
    type: "HOTEL",
    stars: 5,
    rating: 4.6,
    originalPrice: 400000,
    discountPrice: 280000,
    discountRate: 30,
    thumbnailUrl:
      "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4",
  },
  {
    id: "8",
    name: "강릉 씨마크 호텔",
    nameEn: "Seamarq Hotel",
    location: "강원 강릉시",
    type: "HOTEL",
    stars: 5,
    rating: 4.9,
    originalPrice: 900000,
    discountPrice: 810000,
    discountRate: 10,
    thumbnailUrl: "https://images.unsplash.com/photo-1551882547-ff43c63efa17",
  },
  {
    id: "9",
    name: "사인엘 서울",
    nameEn: "SIGNIEL SEOUL",
    location: "서울 송파구",
    type: "HOTEL",
    stars: 5,
    rating: 4.9,
    originalPrice: 1200000,
    discountPrice: 1080000,
    discountRate: 10,
    thumbnailUrl:
      "https://images.unsplash.com/photo-1590490360182-c33d57733427",
  },
  {
    id: "10",
    name: "정동진 썬크루즈 호텔",
    nameEn: "Sun Cruise Hotel",
    location: "강원 강릉시",
    type: "HOTEL",
    stars: 4,
    rating: 4.3,
    originalPrice: 200000,
    discountPrice: 140000,
    discountRate: 30,
    thumbnailUrl:
      "https://images.unsplash.com/photo-1455587734955-081b22074882",
  },
  {
    id: "11",
    name: "메종 글래드 제주",
    nameEn: "Maison Glad Jeju",
    location: "제주 제주시",
    type: "HOTEL",
    stars: 4,
    rating: 4.4,
    originalPrice: 180000,
    discountPrice: 135000,
    discountRate: 25,
    thumbnailUrl:
      "https://images.unsplash.com/photo-1584132967334-10e028bd69f7",
  },
  {
    id: "12",
    name: "여수 유탑 마리나",
    nameEn: "U-TOP Marina Hotel",
    location: "전남 여수시",
    type: "HOTEL",
    stars: 4,
    rating: 4.1,
    originalPrice: 220000,
    discountPrice: 110000,
    discountRate: 50,
    thumbnailUrl:
      "https://images.unsplash.com/photo-1596394516093-501ba68a0ba6",
  },
  {
    id: "13",
    name: "거제 삼성 호텔",
    nameEn: "Geoje Samsung Hotel",
    location: "경남 거제시",
    type: "HOTEL",
    stars: 5,
    rating: 4.5,
    originalPrice: 350000,
    discountPrice: 280000,
    discountRate: 20,
    thumbnailUrl:
      "https://images.unsplash.com/photo-1578683010236-d716f9a3f461",
  },
  {
    id: "14",
    name: "속초 롯데리조트",
    nameEn: "Lotte Resort Sokcho",
    location: "강원 속초시",
    type: "RESORT",
    stars: 5,
    rating: 4.7,
    originalPrice: 400000,
    discountPrice: 340000,
    discountRate: 15,
    thumbnailUrl:
      "https://images.unsplash.com/photo-1610641818989-c2051b5e2cfd",
  },
  {
    id: "15",
    name: "경주 힐튼 호텔",
    nameEn: "Hilton Gyeongju",
    location: "경북 경주시",
    type: "HOTEL",
    stars: 5,
    rating: 4.6,
    originalPrice: 320000,
    discountPrice: 256000,
    discountRate: 20,
    thumbnailUrl:
      "https://images.unsplash.com/photo-1568084680786-a84f91d1153c",
  },
  {
    id: "16",
    name: "양양 서피비치 빌라",
    nameEn: "Surfyy Beach Villa",
    location: "강원 양양군",
    type: "VILLA",
    stars: 3,
    rating: 4.0,
    originalPrice: 500000,
    discountPrice: 250000,
    discountRate: 50,
    thumbnailUrl:
      "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2",
  },
  {
    id: "17",
    name: "통영 금호리조트",
    nameEn: "Kumho Resort Tongyeong",
    location: "경남 통영시",
    type: "RESORT",
    stars: 4,
    rating: 4.2,
    originalPrice: 280000,
    discountPrice: 210000,
    discountRate: 25,
    thumbnailUrl:
      "https://images.unsplash.com/photo-1540541338287-41700207dee6",
  },
  {
    id: "18",
    name: "포천 아도니스 호텔",
    nameEn: "Adonis Hotel",
    location: "경기 포천시",
    type: "HOTEL",
    stars: 3,
    rating: 3.9,
    originalPrice: 150000,
    discountPrice: 105000,
    discountRate: 30,
    thumbnailUrl:
      "https://images.unsplash.com/photo-1618773928121-c32242e63f39",
  },
  {
    id: "19",
    name: "남해 사우스케이프",
    nameEn: "South Cape",
    location: "경남 남해군",
    type: "RESORT",
    stars: 5,
    rating: 5.0,
    originalPrice: 1500000,
    discountPrice: 1350000,
    discountRate: 10,
    thumbnailUrl:
      "https://images.unsplash.com/photo-1573052905904-34ad8c27f0cc",
  },
  {
    id: "20",
    name: "전주 한옥 마을 민박",
    nameEn: "Hanok Village Pension",
    location: "전북 전주시",
    type: "PENSION",
    stars: 2,
    rating: 4.4,
    originalPrice: 120000,
    discountPrice: 96000,
    discountRate: 20,
    thumbnailUrl:
      "https://images.unsplash.com/photo-1580587771525-78b9dba3b914",
  },
];
// ─── Hotel Detail ─────────────────────────────────────────────────────────────
export const mockHotelDetail: HotelDetail = {
  id: "1",
  name: "그랜드 워커힐 서울",
  nameEn: "Grand Walkerhill Seoul",
  location: "서울 광진구",
  type: "HOTEL",
  stars: 5,
  rating: 4.8,
  originalPrice: 550000,
  discountPrice: 440000,
  discountRate: 20,
  thumbnailUrl: "https://images.unsplash.com/photo-1566073771259-6a8506099945",
  description:
    "한강의 아름다운 풍광과 아차산의 맑은 공기를 동시에 즐길 수 있는 도심 속 최고의 휴양지입니다. 프리미엄 서비스와 고품격 인테리어로 최상의 휴식을 선사합니다.",
  images: [
    "https://images.unsplash.com/photo-1566073771259-6a8506099945",
    "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4",
    "https://images.unsplash.com/photo-1551882547-ff43c63efa17",
  ],
  amenities: [
    "실내 수영장",
    "무료 주차",
    "피트니스 센터",
    "룸서비스",
    "사우나",
    "무료 와이파이",
  ],
  address: "서울특별시 광진구 워커힐로 177",
  checkInTime: "15:00",
  checkOutTime: "11:00",
};
