import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { QueryProvider } from "@/lib/providers/QueryProvider";
import { Header } from "@/ui/layouts/Header";
import { UtmInitializer } from "@/ui/patterns/utm/UtmInitializer";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * 루트 레이아웃은 **쿠키를 읽지 않는다.**
 *
 * 예전에는 여기서 getCurrentUser() 를 불러 Header 의 초기 인증 상태를 넘겼다.
 * 그런데 루트 레이아웃은 모든 페이지를 감싸므로, 쿠키를 한 번 읽으면
 * 어떤 페이지도 정적일 수 없다 — ISR 로 만든 /md/[slug] 가 프로덕션에서
 * 500 이 났다 (Page changed from static to dynamic at runtime, reason: cookies).
 *
 * Header 는 이미 클라이언트에서 onAuthStateChange 로 인증을 스스로 판단한다.
 * 서버 조회는 첫 페인트의 깜빡임을 줄이는 최적화였을 뿐이라 없애도 동작한다.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <QueryProvider>
          <UtmInitializer />
          <Header />
          {children}
        </QueryProvider>
      </body>
    </html>
  );
}
