import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { QueryProvider } from "@/lib/providers/QueryProvider";
import { Header } from "@/ui/layouts/Header";
import { UtmInitializer } from "@/ui/patterns/utm/UtmInitializer";
import { getCurrentUser } from "@/infrastructure/supabase/auth";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getCurrentUser();

  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <QueryProvider>
          <UtmInitializer />
          <Header initialAuthenticated={!!user} />
          {children}
        </QueryProvider>
      </body>
    </html>
  );
}
